apiVersion: v1
stringData:
  CELERY_BROKER_URL: ${CELERY_BROKER_URL}
  CSRF_TRUSTED_ORIGINS: http://localhost:8000,https://*.crossbell.io,https://crossbell.io,https://xlog.app,https://*.xlog.app
  DATABASE_URL: psql://postgres:${POSTGRES_PASSWORD}@${POSTGRES_HOST}:5432/txs
  DEBUG: "0"
  DJANGO_ALLOWED_HOSTS: '*'
  DJANGO_SECRET_KEY: ${DJANGO_SECRET_KEY}
  DJANGO_SETTINGS_MODULE: config.settings.production
  ETHEREUM_NODE_URL: https://rpc.crossbell.io
  ETH_L2_NETWORK: "1"
  FORCE_SCRIPT_NAME: /txs/
  PYTHONPATH: /app/
  REDIS_URL: ${REDIS_URI_PREFIX}/1
kind: Secret
metadata:
  name: safe-txs
  namespace: crossbell
type: Opaque
---
apiVersion: v1
stringData:
  # CGW_FLUSH_TOKEN and WEBHOOK_TOKEN must be the same
  CGW_FLUSH_TOKEN: ${WEBHOOK_TOKEN}
  CGW_URL: https://safe.crossbell.io/cgw
  CSRF_TRUSTED_ORIGINS: http://localhost:8000,https://*.crossbell.io,https://crossbell.io,https://xlog.app,https://*.xlog.app
  DEBUG: "false"
  DEFAULT_FILE_STORAGE: django.core.files.storage.FileSystemStorage
  DJANGO_ALLOWED_HOSTS: '*'
  DOCKER_NGINX_VOLUME_ROOT: /nginx
  DOCKER_WEB_VOLUME: .:/app
  FORCE_SCRIPT_NAME: /cfg/
  GUNICORN_BIND_PORT: "8001"
  GUNICORN_BIND_SOCKET: unix:/nginx/gunicorn.socket
  GUNICORN_WEB_RELOAD: "false"
  NGINX_ENVSUBST_OUTPUT_DIR: /etc/nginx/
  POSTGRES_HOST: ${POSTGRES_HOST}
  POSTGRES_NAME: cfg
  POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
  POSTGRES_PORT: "5432"
  POSTGRES_USER: postgres
  ROOT_LOG_LEVEL: WARNING
  SECRET_KEY: ${SECRET_KEY}
kind: Secret
metadata:
  name: safe-cfg
  namespace: crossbell
type: Opaque
---
apiVersion: v1
stringData:
  CHAIN_INFO_REQUEST_TIMEOUT: "15000"
  CONFIG_SERVICE_URI: https://safe.crossbell.io/cfg
  EXCHANGE_API_BASE_URI: http://api.exchangeratesapi.io/latest
  EXCHANGE_API_KEY: ${EXCHANGE_API_KEY}
  FEATURE_FLAG_NESTED_DECODING: "true"
  INTERNAL_CLIENT_CONNECT_TIMEOUT: "10000"
  LOG_ALL_ERROR_RESPONSES: "true"
  REDIS_URI: ${REDIS_URI_PREFIX}/0
  REDIS_URI_MAINNET: ${REDIS_URI_PREFIX}/0
  ROCKET_ADDRESS: 0.0.0.0
  ROCKET_LOG_LEVEL: normal
  ROCKET_PORT: "3666"
  ROCKET_SECRET_KEY: ${ROCKET_SECRET_KEY}
  RUST_LOG: warn
  SAFE_APP_INFO_REQUEST_TIMEOUT: "10000"
  SCHEME: http
  WEBHOOK_TOKEN: ${WEBHOOK_TOKEN}
kind: Secret
metadata:
  name: safe-cgw
  namespace: crossbell
type: Opaque
