apiVersion: v1
kind: Secret
metadata:
  name: safe-cfg
  namespace: crossbell
type: Opaque
stringData:
  # CGW_FLUSH_TOKEN and WEBHOOK_TOKEN must be the same
  CGW_FLUSH_TOKEN: "<WEBHOOK_TOKEN>"
  CGW_URL: "https://safe-client.crossbell.io"
  CSRF_TRUSTED_ORIGINS: "http://localhost:8000,https://*.crossbell.io,https://crossbell.io,https://xlog.app,https://*.xlog.app"
  DEBUG: "false"
  DEFAULT_FILE_STORAGE: "django.core.files.storage.FileSystemStorage"
  DJANGO_ALLOWED_HOSTS: "*"
  DOCKER_NGINX_VOLUME_ROOT: "/nginx"
  DOCKER_WEB_VOLUME: ".:/app"
  FORCE_SCRIPT_NAME: "/cfg/"
  GUNICORN_BIND_PORT: "8001"
  GUNICORN_BIND_SOCKET: "unix:/nginx/gunicorn.socket"
  GUNICORN_WEB_RELOAD: "false"
  NGINX_ENVSUBST_OUTPUT_DIR: "/etc/nginx/"
  POSTGRES_HOST: "<POSTGRES_HOST>"
  POSTGRES_NAME: "safe_cfg"
  POSTGRES_PASSWORD: "<POSTGRES_PASSWORD>"
  POSTGRES_PORT: "5432"
  POSTGRES_USER: "postgres"
  ROOT_LOG_LEVEL: "WARNING"
  SECRET_KEY: "<SECRET_KEY>"
