apiVersion: v1
kind: Secret
metadata:
  name: safe-txs
  namespace: crossbell
type: Opaque
stringData:
  CELERY_BROKER_URL: "<CELERY_BROKER_URL>"
  CSRF_TRUSTED_ORIGINS: "http://localhost:8000,https://*.crossbell.io,https://crossbell.io,https://xlog.app,https://*.xlog.app"
  DATABASE_URL: "psql://postgres:<POSTGRES_PASSWORD>@<POSTGRES_HOST>:5432/safe_txs"
  DEBUG: "0"
  DJANGO_ALLOWED_HOSTS: "*"
  DJANGO_SECRET_KEY: "<DJANGO_SECRET_KEY>"
  DJANGO_SETTINGS_MODULE: "config.settings.production"
  ETHEREUM_NODE_URL: "https://rpc.crossbell.io"
  ETH_L2_NETWORK: "1"
  FORCE_SCRIPT_NAME: "/txs/"
  PYTHONPATH: "/app/"
  REDIS_URL: "<REDIS_URI_PREFIX>/1"
