# build and push docker image to docker hub
name: Build & Deploy Prod

on:
  push:
    branches:
      - "main"

env:
  REGION_ID: us-east-1
  ACK_CLUSTER_ID: cfc647c22fd6848b5a602ad4d7470632b

jobs:
  deploy-prod:
    uses: NaturalSelectionLabs/Daedalus/.github/workflows/deploy-v3-tpl.yaml@main
    with:
      images: safe
      tag: ""
      cluster: prod
      namespace: crossbell
      releaseName: safe
      revision: main
      dir: deploy/prod
    secrets:
      ARGOCD_TOKEN: ${{ secrets.ARGOCD_TOKEN }}
